name: Update SDK Documentation

# This workflow runs on merges to main to automatically update SDK docs
# by creating a PR when changes are needed.

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sdk-docs:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate Marvin App token
        id: marvin-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.MARVIN_APP_ID }}
          private-key: ${{ secrets.MARVIN_APP_PRIVATE_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --python 3.12

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Generate SDK documentation
        run: |
          echo "🔄 Generating SDK documentation..."
          just api-ref-all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.marvin-token.outputs.token }}
          commit-message: "chore: Update SDK documentation"
          title: "chore: Update SDK documentation"
          body: |
            This PR updates the auto-generated SDK documentation to reflect the latest source code changes.

            📚 Documentation is automatically generated from the source code docstrings and type annotations.

            **Note:** This PR is fully automated and will update itself with any subsequent changes to the SDK, or close automatically if the documentation becomes up-to-date through other means. Feel free to leave it open until you're ready to merge.

            🤖 Generated by Marvin
          branch: marvin/update-sdk-docs
          labels: |
            ignore in release notes
          delete-branch: true
          author: "marvin-context-protocol[bot] <225465937+marvin-context-protocol[bot]@users.noreply.github.com>"
          committer: "marvin-context-protocol[bot] <225465937+marvin-context-protocol[bot]@users.noreply.github.com>"

      - name: Summary
        run: |
          echo "✅ SDK documentation generation workflow completed"
          echo "PR will be created if there are changes, or closed if documentation is already up to date"
